# Generated by Django 3.2 on 2021-05-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_numbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=16)),
                ('second_name', models.CharField(default='', max_length=16)),
                ('third_name', models.CharField(default='', max_length=16)),
                ('date', models.DateField(default='')),
                ('passport_field', models.CharField(default='', max_length=10, unique='True')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(default='')),
                ('check_out_date', models.DateField(default='')),
                ('phone_number', models.CharField(default='', max_length=16)),
                ('complementary_services', models.CharField(default='', max_length=50)),
                ('execution', models.BooleanField(default=False)),
                ('room_number', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_numbers.hotelnumber')),
            ],
        ),
    ]
