# Generated by Django 3.2 on 2021-05-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_order_executed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_date', models.DateField(default='')),
                ('time_out_date', models.DateField(default='')),
                ('reason', models.CharField(default='', max_length=200, null=True)),
                ('client_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
