# Generated by Django 3.2 on 2021-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='case_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
