# Generated by Django 3.2 on 2021-05-23 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0006_rename_client_id_blacklist_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
            ],
            options={
                'verbose_name': 'Справочник доп. услуг',
            },
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name': 'Черный список'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.CreateModel(
            name='AdditionalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default='')),
                ('execution', models.BooleanField(default=False)),
                ('coast', models.FloatField(null=True)),
                ('Menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.menulist')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.servicelist')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ (дополнительные услуги)',
                'verbose_name_plural': 'Заказы (дополнительные услуги)',
            },
        ),
    ]
