# Generated by Django 3.2 on 2021-05-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210523_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalorder',
            name='execution',
        ),
    ]
