# Generated by Django 3.2 on 2021-05-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('coast', models.FloatField(null=True)),
                ('number_of_room', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HotelNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_residents', models.IntegerField(default=0)),
                ('coast_per_day', models.FloatField(null=True)),
                ('room_occupancy', models.BooleanField(default=False)),
                ('room_condition', models.BooleanField(default=True)),
                ('number_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_numbers.numbertype')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
