# Generated by Django 3.2 on 2021-05-27 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_numbers', '0002_hotelnumber_complementary_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('coast', models.FloatField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('dirty_staff', models.IntegerField(default=0)),
                ('condition', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WashHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('condition', models.BooleanField(default=False)),
                ('coast', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hotelnumber',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoomDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel_numbers.storage')),
                ('number_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel_numbers.hotelnumber')),
            ],
        ),
        migrations.CreateModel(
            name='DirtyLineal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel_numbers.storage')),
                ('wash_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel_numbers.washhouse')),
            ],
        ),
    ]
