# Generated by Django 3.2 on 2021-05-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_numbers', '0003_auto_20210527_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dirtylineal',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='dirtylineal',
            old_name='wash_id',
            new_name='wash',
        ),
        migrations.RenameField(
            model_name='roomdecoration',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='roomdecoration',
            old_name='number_id',
            new_name='number',
        ),
    ]
