# Generated by Django 3.2 on 2021-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_numbers', '0005_auto_20210527_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='dirty_staff',
            field=models.IntegerField(default=0),
        ),
    ]
