# Generated by Django 3.2 on 2021-05-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_numbers', '0007_provider_stafforder'),
    ]

    operations = [
        migrations.AddField(
            model_name='washhouse',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_numbers.storage'),
        ),
        migrations.DeleteModel(
            name='DirtyLineal',
        ),
    ]
