# Generated by Django 3.2 on 2021-05-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_numbers', '0008_auto_20210528_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafforder',
            name='stuff',
        ),
    ]
