# Generated by Django 3.2 on 2021-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='bonuses',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='payment',
            field=models.FloatField(null=True),
        ),
    ]
