# Generated by Django 3.2 on 2021-05-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_remove_worker_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
