# Generated by Django 3.2 on 2021-05-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_alter_worker_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
