# Generated by Django 3.2 on 2021-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_worker_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='bonuses',
        ),
        migrations.AddField(
            model_name='worker',
            name='bonuses',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='fine',
            field=models.FloatField(null=True),
        ),
    ]
