# Generated by Django 3.2 on 2021-05-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_vacation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='vacation',
            options={'verbose_name': 'Отпуск', 'verbose_name_plural': 'Отпуска'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
